name: Policy Assistant CI

on:
  push:
    paths:
      - "projects/02_genai_policy_assistant/**"
      - ".github/workflows/policy.yml"
      - "requirements.txt"
  pull_request:
    paths:
      - "projects/02_genai_policy_assistant/**"
      - ".github/workflows/policy.yml"
      - "requirements.txt"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - name: Run project 02 tests
        run: pytest -q projects/02_genai_policy_assistant/tests
